In [1]:
import pandas as pd
import numpy as np
import requests
import time
import json
from datetime import datetime, timedelta
from dateutil.relativedelta import *
import calendar

In [2]:
weather_df=pd.read_csv('weather_csv.csv')

In [3]:
weather_df['hour_formatted']=weather_df['hour']/100

In [4]:
weather_df.head(20)

,date,feels_like,heat_index,hour,precipitation,sunrise,sunset,temperature,weather_description,hour_formatted
0,2018-04-01,62,62,0,0.0,07:20 AM,07:50 PM,62,Cloudy,0.0
1,2018-04-01,62,62,100,0.0,07:20 AM,07:50 PM,62,Cloudy,1.0
2,2018-04-01,61,62,200,0.0,07:20 AM,07:50 PM,62,Patchy rain possible,2.0
3,2018-04-01,61,61,300,0.0,07:20 AM,07:50 PM,61,Patchy rain possible,3.0
4,2018-04-01,61,61,400,0.0,07:20 AM,07:50 PM,61,Patchy rain possible,4.0
5,2018-04-01,61,61,500,0.0,07:20 AM,07:50 PM,61,Cloudy,5.0
6,2018-04-01,61,62,600,0.0,07:20 AM,07:50 PM,61,Cloudy,6.0
7,2018-04-01,63,64,700,0.0,07:20 AM,07:50 PM,63,Cloudy,7.0
8,2018-04-01,64,66,800,0.1,07:20 AM,07:50 PM,65,Patchy rain possible,8.0
9,2018-04-01,66,67,900,0.1,07:20 AM,07:50 PM,67,Patchy rain possible,9.0
10,2018-04-01,69,71,1000,0.1,07:20 AM,07:50 PM,69,Patchy rain possible,10.0
11,2018-04-01,74,74,1100,0.0,07:20 AM,07:50 PM,72,Cloudy,11.0
12,2018-04-01,78,78,1200,0.0,07:20 AM,07:50 PM,75,Cloudy,12.0
13,2018-04-01,78,78,1300,0.0,07:20 AM,07:50 PM,75,Cloudy,13.0
14,2018-04-01,79,79,1400,0.0,07:20 AM,07:50 PM,76,Patchy rain possible,14.0
15,2018-04-01,79,79,1500,0.1,07:20 AM,07:50 PM,76,Patchy rain possible,15.0
16,2018-04-01,78,78,1600,0.0,07:20 AM,07:50 PM,75,Patchy rain possible,16.0
17,2018-04-01,76,76,1700,0.0,07:20 AM,07:50 PM,74,Patchy rain possible,17.0
18,2018-04-01,75,75,1800,0.0,07:20 AM,07:50 PM,72,Patchy rain possible,18.0
19,2018-04-01,70,72,1900,0.0,07:20 AM,07:50 PM,70,Patchy rain possible,19.0

In [5]:
temp_groupby=weather_df.groupby('temperature').agg({"hour":"count"})

In [6]:
scooter_df=pd.read_csv('Dockless_Vehicle_Trips.csv')

/Users/bbobba/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
scooter_df.head()

,ID,Device ID,Vehicle Type,Trip Duration,Trip Distance,Start Time,End Time,Modified Date,Month,Hour,Day of Week,Council District (Start),Council District (End),Origin Cell ID,Destination Cell ID,Year,Start Latitude,Start Longitude,End Latitude,End Longitude
0,000000cb-78a9-4b95-8ead-37c797abcf37,ad14e63b-940d-4ca3-84c6-0131147fba45,scooter,358.0,915.0,06/29/2018 05:30:00 PM,06/29/2018 05:30:00 PM,12/12/2018 09:36:14 PM,6.0,17.0,5.0,5.0,9.0,013445,013916,2018.0,30.263,-97.762,30.259,-97.754
1,00001b5f-46aa-4b26-a12f-d7b4d3c69834,c5a230c9-7e80-4464-862f-f2b23f61d6d3,scooter,226.0,839.0,11/30/2018 11:00:00 AM,11/30/2018 11:00:00 AM,12/13/2018 03:43:44 PM,11.0,11.0,5.0,9.0,9.0,014556,015186,2018.0,30.283,-97.745,30.284,-97.737
2,00002334-2f2b-41a0-9a04-8ff66be39f40,5a9f7815-bf0c-4fef-8bac-60efd4f23b10,scooter,324.0,1206.0,10/02/2018 03:15:00 PM,10/02/2018 03:30:00 PM,12/13/2018 03:49:54 PM,10.0,15.0,2.0,9.0,9.0,015344,015032,2018.0,30.285,-97.734,30.291,-97.738
3,0000261e-c0f0-4fb1-9947-1606dfe4ddcf,41fa0cf0-f433-4b3a-89f5-2c6cec6c367d,scooter,1096.0,0.0,09/02/2018 04:45:00 PM,09/02/2018 05:00:00 PM,12/13/2018 03:53:09 PM,9.0,16.0,0.0,9.0,9.0,014707,014081,2018.0,30.268,-97.743,30.276,-97.752
4,00002c70-678b-4c09-a32c-da0266e329c6,ddd4bbc3-114e-4cbc-b078-860e3c28b11b,scooter,408.0,1144.0,09/28/2018 11:45:00 AM,09/28/2018 11:45:00 AM,12/12/2018 10:24:56 PM,9.0,11.0,5.0,3.0,3.0,016114,015642,2018.0,30.242,-97.721,30.244,-97.729

In [ ]:
scooter_df['start_time_full_date']=pd.to_datetime(scooter_df['Start Time'])

In [ ]:
scooter_df.head()

In [ ]:
scooter_df.count()

In [ ]:
scooter_df.dropna(subset=['Start Time'], inplace=True)
scooter_df.count()

In [ ]:
scooter_df['start_time_str']=scooter_df['start_time_full_date'].apply(lambda x: x.strftime('%Y-%m-%d'))

In [ ]:
scooter_df.head(10)

In [ ]:
#Creation of average coordinates per Origin and Destination Cell and update scooter dataframe with those values
#Origin cell
df_coord1 = scooter_df[["Origin Cell ID","Start Latitude","Start Longitude"]]
df_coord1 = df_coord1.groupby(["Origin Cell ID"], as_index=False).mean()

#Destination cell
df_coord2 = scooter_df[["Destination Cell ID","End Latitude","End Longitude"]]
df_coord2 = df_coord2.groupby(["Destination Cell ID"], as_index=False).mean()

In [ ]:
#Update on Origin cell
left_a = scooter_df.set_index('Origin Cell ID')
right_a = df_coord1.set_index('Origin Cell ID')
res = left_a.reindex(columns=left_a.columns.union(right_a.columns))
res.update(right_a)
res.reset_index(inplace=True)

In [ ]:
#Update on Destination cell 
left_a = res.set_index('Destination Cell ID')
right_a = df_coord2.set_index('Destination Cell ID')
res = left_a.reindex(columns=left_a.columns.union(right_a.columns))
res.update(right_a)
res.reset_index(inplace=True)

In [ ]:
scooter_df = res

In [ ]:
df=pd.merge(scooter_df,weather_df, how='left', left_on=['start_time_str', 'Hour'], right_on=['date','hour_formatted'], sort=True)

In [ ]:
df.head()

In [ ]:
df_scooter_only=df.loc[df['Vehicle Type']=='scooter']

In [ ]:
df_scooter_only.to_csv("scooter_weather.csv", index=False)